"""
Semantic Search Engine — Module 03 Project (Solution)

A CLI tool that embeds documents, indexes them with FAISS, and finds
relevant content by meaning. Uses sentence-transformers for local
embeddings (no API key needed).

Run: python solution.py
"""

import numpy as np
import faiss
from sentence_transformers import SentenceTransformer


# ---------------------------------------------------------------------------
# Sample document
# ---------------------------------------------------------------------------

DOCUMENT = """\
Getting Started with Authentication

Passwords and Hashing

Storing passwords in plain text is a critical security vulnerability. Always \
hash passwords using a modern algorithm such as bcrypt, scrypt, or Argon2. \
These algorithms are designed to be computationally expensive, which slows \
down brute-force attacks. Add a unique salt to each password before hashing \
to prevent rainbow table lookups. Never use fast hashing functions like MD5 \
or SHA-256 for password storage because they can be computed billions of \
times per second on modern hardware.

OAuth 2.0 and Third-Party Login

OAuth 2.0 allows users to log in using their existing accounts from providers \
like Google, GitHub, or Microsoft. The application redirects the user to the \
provider's login page, and after successful authentication, the provider \
returns an authorization code. The application exchanges this code for an \
access token, which grants limited access to the user's profile information. \
OAuth is preferred for consumer-facing applications because it eliminates the \
need for users to create yet another password. Always validate the state \
parameter to prevent cross-site request forgery attacks.

API Keys and Service Authentication

API keys are long, randomly generated strings used to authenticate \
machine-to-machine communication. Unlike passwords, API keys are not tied to \
a human user but to an application or service account. Store API keys in \
environment variables or a secrets manager, never in source code or version \
control. Rotate API keys regularly and implement key scoping so each key has \
only the minimum permissions required. Monitor API key usage for anomalies \
that might indicate a compromised key.

Session Management

After a user authenticates, the server creates a session to track the logged-in \
state. Sessions are typically stored server-side with a session ID sent to the \
client as an HTTP cookie. Set cookies with the Secure, HttpOnly, and SameSite \
flags to prevent interception and cross-site attacks. Implement session \
expiration with both idle timeouts and absolute timeouts. For stateless \
architectures, JSON Web Tokens (JWTs) can replace server-side sessions, but \
JWTs come with their own challenges: they cannot be revoked once issued unless \
you maintain a blocklist, and they increase the size of every request.

Multi-Factor Authentication

Multi-factor authentication (MFA) adds a second verification step beyond the \
password. Common second factors include time-based one-time passwords (TOTP) \
generated by apps like Google Authenticator, SMS codes, hardware security keys \
like YubiKey, and biometric verification. TOTP is preferred over SMS because \
SMS is vulnerable to SIM-swapping attacks. For high-security applications, \
require MFA for all users. For consumer applications, offer MFA as an option \
and encourage adoption through user education and simplified setup flows.\
"""


# ---------------------------------------------------------------------------
# Chunker
# ---------------------------------------------------------------------------

class RecursiveChunker:
    """Split text into chunks by paragraphs, then by sentences if needed."""

    def __init__(self, max_chunk_size: int = 300, overlap: int = 50):
        self.max_chunk_size = max_chunk_size
        self.overlap = overlap

    def chunk(self, text: str) -> list[str]:
        sections = [s.strip() for s in text.split("\n\n") if s.strip()]
        chunks = []
        for section in sections:
            if len(section) <= self.max_chunk_size:
                chunks.append(section)
            else:
                chunks.extend(self._split_by_sentences(section))
        return self._add_overlap(chunks)

    def _split_by_sentences(self, text: str) -> list[str]:
        sentences = []
        for part in text.replace("? ", "?|").replace(". ", ".|").replace("! ", "!|").split("|"):
            part = part.strip()
            if part:
                sentences.append(part)

        chunks, current = [], ""
        for sentence in sentences:
            candidate = f"{current} {sentence}".strip() if current else sentence
            if len(candidate) <= self.max_chunk_size:
                current = candidate
            else:
                if current:
                    chunks.append(current)
                current = sentence
        if current:
            chunks.append(current)
        return chunks

    def _add_overlap(self, chunks: list[str]) -> list[str]:
        if self.overlap == 0 or len(chunks) <= 1:
            return chunks
        result = [chunks[0]]
        for i in range(1, len(chunks)):
            prev_words = chunks[i - 1].split()
            overlap_words = prev_words[-self.overlap // 5:] if len(prev_words) > self.overlap // 5 else prev_words
            overlap_text = " ".join(overlap_words)
            result.append(f"{overlap_text} {chunks[i]}")
        return result


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def embed(texts: list[str], model: SentenceTransformer) -> np.ndarray:
    """Embed a list of texts and return L2-normalized vectors."""
    vectors = model.encode(texts, convert_to_numpy=True, normalize_embeddings=True)
    return vectors.astype("float32")


def build_index(vectors: np.ndarray) -> faiss.IndexFlatIP:
    """Build a FAISS inner-product index from normalized vectors."""
    dim = vectors.shape[1]
    index = faiss.IndexFlatIP(dim)
    index.add(vectors)
    return index


def search(query: str, model: SentenceTransformer, index: faiss.IndexFlatIP,
           chunks: list[str], top_k: int = 3) -> list[tuple[str, float]]:
    """Embed a query and return the top-k matching chunks with scores."""
    query_vec = embed([query], model)
    scores, indices = index.search(query_vec, top_k)
    return [(chunks[i], float(scores[0][j])) for j, i in enumerate(indices[0])]


# ---------------------------------------------------------------------------
# Demo 1: Embed and Inspect
# ---------------------------------------------------------------------------

def demo_embed_inspect(model: SentenceTransformer):
    print("--- 1. Embed and Inspect a Sentence ---\n")

    sentence = "Authentication is the process of verifying a user's identity."
    vec = embed([sentence], model)[0]

    print(f"  Sentence : {sentence}")
    print(f"  Dimension: {vec.shape[0]}")
    print(f"  First 10 : {np.round(vec[:10], 4).tolist()}")
    print(f"  L2 norm  : {np.linalg.norm(vec):.4f}  (should be ~1.0)")
    print()


# ---------------------------------------------------------------------------
# Demo 2: Semantic Similarity Matrix
# ---------------------------------------------------------------------------

def demo_similarity_matrix(model: SentenceTransformer):
    print("--- 2. Semantic Similarity Matrix ---\n")

    sentences = [
        "How do I reset my password?",
        "I forgot my login credentials.",
        "What is OAuth 2.0?",
        "How does third-party authentication work?",
        "What is the weather forecast for tomorrow?",
    ]

    vecs = embed(sentences, model)
    similarity = vecs @ vecs.T

    # Print labels
    labels = [f"S{i+1}" for i in range(len(sentences))]
    header = "       " + "  ".join(f"{l:>6}" for l in labels)
    print(header)

    for i, row in enumerate(similarity):
        vals = "  ".join(f"{v:6.3f}" for v in row)
        print(f"  {labels[i]}   {vals}")

    print()
    print("  Sentences:")
    for i, s in enumerate(sentences):
        print(f"    S{i+1}: {s}")

    print()
    print("  Note: S1-S2 and S3-S4 are semantically similar (high scores).")
    print("  S5 is unrelated to the others (low scores).")
    print()


# ---------------------------------------------------------------------------
# Demo 3: Document Chunking
# ---------------------------------------------------------------------------

def demo_chunking():
    print("--- 3. Document Chunking ---\n")

    chunker = RecursiveChunker(max_chunk_size=300, overlap=50)
    chunks = chunker.chunk(DOCUMENT)

    for i, chunk in enumerate(chunks):
        print(f"  Chunk {i+1} ({len(chunk)} chars):")
        preview = chunk[:120].replace("\n", " ")
        if len(chunk) > 120:
            preview += "..."
        print(f"    {preview}")
    print()
    print(f"  Total chunks: {len(chunks)}")
    print()

    return chunks


# ---------------------------------------------------------------------------
# Demo 4: Build Index and Search
# ---------------------------------------------------------------------------

def demo_search(model: SentenceTransformer, chunks: list[str]):
    print("--- 4. Build Index and Search ---\n")

    vecs = embed(chunks, model)
    index = build_index(vecs)

    queries = [
        "How should I store passwords securely?",
        "What is the difference between OAuth and API keys?",
        "How do sessions and cookies work?",
    ]

    for query in queries:
        print(f"  Query: \"{query}\"")
        results = search(query, model, index, chunks, top_k=3)
        for rank, (chunk, score) in enumerate(results, 1):
            preview = chunk[:100].replace("\n", " ")
            print(f"    #{rank} (score: {score:.4f}): {preview}...")
        print()

    return index, vecs


# ---------------------------------------------------------------------------
# Demo 5: Similarity Threshold
# ---------------------------------------------------------------------------

def demo_threshold(model: SentenceTransformer, chunks: list[str], index: faiss.IndexFlatIP):
    print("--- 5. Similarity Threshold Demo ---\n")

    irrelevant_query = "How do I make chocolate chip cookies?"
    print(f"  Query: \"{irrelevant_query}\"")
    print(f"  (This query has nothing to do with the documents.)\n")

    results = search(irrelevant_query, model, index, chunks, top_k=3)

    print("  Results WITHOUT threshold (vector search always returns something):")
    for rank, (chunk, score) in enumerate(results, 1):
        preview = chunk[:90].replace("\n", " ")
        print(f"    #{rank} (score: {score:.4f}): {preview}...")

    print()

    threshold = 0.35
    print(f"  Results WITH threshold (score >= {threshold}):")
    filtered = [(chunk, score) for chunk, score in results if score >= threshold]
    if filtered:
        for rank, (chunk, score) in enumerate(filtered, 1):
            preview = chunk[:90].replace("\n", " ")
            print(f"    #{rank} (score: {score:.4f}): {preview}...")
    else:
        print("    (no results above threshold — correctly rejected irrelevant query)")

    print()
    print("  Takeaway: vector search always returns the nearest neighbors, even")
    print("  if they are irrelevant. Use a similarity threshold to filter results.")
    print()


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    print("=" * 60)
    print("  Semantic Search Engine")
    print("=" * 60)
    print()

    print("  Loading embedding model (first run downloads ~80 MB)...")
    model = SentenceTransformer("all-MiniLM-L6-v2")
    print("  Model loaded.\n")

    demo_embed_inspect(model)
    demo_similarity_matrix(model)
    chunks = demo_chunking()
    index, _ = demo_search(model, chunks)
    demo_threshold(model, chunks, index)

    print("=" * 60)
    print("  Done!")
    print("=" * 60)


if __name__ == "__main__":
    main()
