"""
RAG Q&A — Module 07 Project (Solution)

A CLI tool that answers questions about a technical document using
Retrieval-Augmented Generation. Retrieves relevant passages, injects
them into the prompt, and generates grounded answers with citations.

Run: python solution.py
"""

import os
import numpy as np
import faiss
from pathlib import Path
from dotenv import load_dotenv
from litellm import completion, completion_cost
from sentence_transformers import SentenceTransformer

load_dotenv(Path(__file__).resolve().parent.parent.parent / ".env")

MODEL = os.getenv("LLM_MODEL", "anthropic/claude-sonnet-4-20250514")


# ---------------------------------------------------------------------------
# Sample document
# ---------------------------------------------------------------------------

DOCUMENT = """\
Getting Started with Authentication

Passwords and Hashing

Storing passwords in plain text is a critical security vulnerability. Always \
hash passwords using a modern algorithm such as bcrypt, scrypt, or Argon2. \
These algorithms are designed to be computationally expensive, which slows \
down brute-force attacks. Add a unique salt to each password before hashing \
to prevent rainbow table lookups. Never use fast hashing functions like MD5 \
or SHA-256 for password storage because they can be computed billions of \
times per second on modern hardware.

OAuth 2.0 and Third-Party Login

OAuth 2.0 allows users to log in using their existing accounts from providers \
like Google, GitHub, or Microsoft. The application redirects the user to the \
provider's login page, and after successful authentication, the provider \
returns an authorization code. The application exchanges this code for an \
access token, which grants limited access to the user's profile information. \
OAuth is preferred for consumer-facing applications because it eliminates the \
need for users to create yet another password. Always validate the state \
parameter to prevent cross-site request forgery attacks.

API Keys and Service Authentication

API keys are long, randomly generated strings used to authenticate \
machine-to-machine communication. Unlike passwords, API keys are not tied to \
a human user but to an application or service account. Store API keys in \
environment variables or a secrets manager, never in source code or version \
control. Rotate API keys regularly and implement key scoping so each key has \
only the minimum permissions required. Monitor API key usage for anomalies \
that might indicate a compromised key.

Session Management

After a user authenticates, the server creates a session to track the logged-in \
state. Sessions are typically stored server-side with a session ID sent to the \
client as an HTTP cookie. Set cookies with the Secure, HttpOnly, and SameSite \
flags to prevent interception and cross-site attacks. Implement session \
expiration with both idle timeouts and absolute timeouts. For stateless \
architectures, JSON Web Tokens (JWTs) can replace server-side sessions, but \
JWTs come with their own challenges: they cannot be revoked once issued unless \
you maintain a blocklist, and they increase the size of every request.

Multi-Factor Authentication

Multi-factor authentication (MFA) adds a second verification step beyond the \
password. Common second factors include time-based one-time passwords (TOTP) \
generated by apps like Google Authenticator, SMS codes, hardware security keys \
like YubiKey, and biometric verification. TOTP is preferred over SMS because \
SMS is vulnerable to SIM-swapping attacks. For high-security applications, \
require MFA for all users. For consumer applications, offer MFA as an option \
and encourage adoption through user education and simplified setup flows.

Token-Based Authentication

Token-based authentication uses signed tokens instead of server-side sessions. \
The most common format is JSON Web Tokens (JWT), which contain a header, \
payload, and signature. The server signs the token with a secret key, and the \
client sends it with every request. The server verifies the signature without \
needing to look up a session. Access tokens should be short-lived (15-60 \
minutes) to limit the damage if compromised. Refresh tokens can be longer-lived \
but must be stored securely and support revocation.

Rate Limiting and Brute Force Protection

Rate limiting restricts how many requests a client can make in a given time \
window. For login endpoints, limit to 5-10 attempts per minute per IP address \
or username. After exceeding the limit, return HTTP 429 (Too Many Requests) \
with a Retry-After header. Implement progressive delays: each failed attempt \
increases the wait time. For API endpoints, use token bucket or sliding window \
algorithms. Consider using CAPTCHAs after repeated failures to distinguish \
humans from automated attacks.

HTTPS and Transport Security

All authentication traffic must use HTTPS (TLS 1.2 or higher). HTTP transmits \
credentials in plain text, making them vulnerable to interception. Configure \
HSTS (HTTP Strict Transport Security) headers to prevent downgrade attacks. \
Use strong cipher suites and disable older protocols like TLS 1.0 and 1.1. \
For APIs, enforce TLS on all endpoints, not just authentication. Pin \
certificates in mobile applications to prevent man-in-the-middle attacks \
using compromised certificate authorities.\
"""


# ---------------------------------------------------------------------------
# Step 1: Chunking
# ---------------------------------------------------------------------------

def chunk_document(text: str, max_chunk_size: int = 300,
                   overlap: int = 50) -> list[dict]:
    """Split a document into chunks with metadata."""
    raw_sections = [s.strip() for s in text.split("\n\n") if s.strip()]

    # Pair headers with their content
    sections = []
    current_title = "Introduction"
    current_body = ""

    for block in raw_sections:
        if len(block) < 60 and "." not in block:
            if current_body:
                sections.append((current_title, current_body.strip()))
            current_title = block
            current_body = ""
        else:
            current_body += (" " if current_body else "") + block

    if current_body:
        sections.append((current_title, current_body.strip()))

    # Chunk each section
    chunks = []
    for section_title, body in sections:
        if len(body) <= max_chunk_size:
            chunks.append({
                "text": body,
                "metadata": {
                    "section": section_title,
                    "chunk_index": len(chunks),
                },
            })
        else:
            sentence_chunks = _split_by_sentences(body, max_chunk_size)
            sentence_chunks = _add_overlap(sentence_chunks, overlap)
            for sc in sentence_chunks:
                chunks.append({
                    "text": sc,
                    "metadata": {
                        "section": section_title,
                        "chunk_index": len(chunks),
                    },
                })

    return chunks


def _split_by_sentences(text: str, max_size: int) -> list[str]:
    """Split text into chunks on sentence boundaries."""
    sentences = []
    for part in text.replace("? ", "?|").replace(". ", ".|").replace("! ", "!|").split("|"):
        part = part.strip()
        if part:
            sentences.append(part)

    chunks, current = [], ""
    for sentence in sentences:
        candidate = f"{current} {sentence}".strip() if current else sentence
        if len(candidate) <= max_size:
            current = candidate
        else:
            if current:
                chunks.append(current)
            current = sentence
    if current:
        chunks.append(current)
    return chunks


def _add_overlap(chunks: list[str], overlap: int) -> list[str]:
    """Add overlap from the end of each chunk to the start of the next."""
    if overlap == 0 or len(chunks) <= 1:
        return chunks
    result = [chunks[0]]
    for i in range(1, len(chunks)):
        prev_words = chunks[i - 1].split()
        n_words = max(1, overlap // 5)
        overlap_words = prev_words[-n_words:] if len(prev_words) > n_words else prev_words
        overlap_text = " ".join(overlap_words)
        result.append(f"{overlap_text} {chunks[i]}")
    return result


# ---------------------------------------------------------------------------
# Step 2: Embedding & indexing
# ---------------------------------------------------------------------------

def embed(texts: list[str], model: SentenceTransformer) -> np.ndarray:
    """Embed a list of texts and return L2-normalized vectors."""
    vectors = model.encode(texts, convert_to_numpy=True,
                           normalize_embeddings=True)
    return vectors.astype("float32")


def build_rag_index(chunks: list[dict],
                    model: SentenceTransformer) -> tuple[faiss.IndexFlatIP, np.ndarray]:
    """Embed chunk texts and build a FAISS inner-product index."""
    texts = [c["text"] for c in chunks]
    vectors = embed(texts, model)
    dim = vectors.shape[1]
    index = faiss.IndexFlatIP(dim)
    index.add(vectors)
    return index, vectors


# ---------------------------------------------------------------------------
# Step 3: Retrieval
# ---------------------------------------------------------------------------

def retrieve(query: str, model: SentenceTransformer,
             index: faiss.IndexFlatIP, chunks: list[dict],
             top_k: int = 3, threshold: float = 0.3) -> list[dict]:
    """Retrieve the most relevant chunks for a query."""
    query_vec = embed([query], model)
    scores, indices = index.search(query_vec, top_k)

    results = []
    for j, i in enumerate(indices[0]):
        score = float(scores[0][j])
        if score >= threshold:
            results.append({
                "text": chunks[i]["text"],
                "metadata": chunks[i]["metadata"],
                "score": score,
            })

    results.sort(key=lambda x: x["score"], reverse=True)
    return results


# ---------------------------------------------------------------------------
# Step 4: RAG prompt
# ---------------------------------------------------------------------------

SYSTEM_PROMPT = """\
You are a helpful assistant. Answer questions based ONLY on the provided \
context below. If the context doesn't contain enough information to answer \
the question, say "I don't have enough information in my documents to answer \
that question."

Cite your sources using [Source N] format after each claim. Only cite sources \
that directly support your statement. Do not make up information that is not \
in the provided context.\
"""


def build_rag_prompt(question: str,
                     retrieved: list[dict]) -> list[dict]:
    """Build the messages list for a RAG query."""
    if not retrieved:
        user_content = (
            "Context:\nNo relevant information was found in the documents.\n\n"
            f"Question: {question}"
        )
    else:
        context_parts = []
        for i, chunk in enumerate(retrieved, 1):
            section = chunk["metadata"]["section"]
            context_parts.append(
                f"[Source {i}: {section}]\n{chunk['text']}"
            )
        context = "\n\n".join(context_parts)
        user_content = f"Context:\n{context}\n\nQuestion: {question}"

    return [
        {"role": "system", "content": SYSTEM_PROMPT},
        {"role": "user", "content": user_content},
    ]


# ---------------------------------------------------------------------------
# Step 5: Generate
# ---------------------------------------------------------------------------

def ask(question: str, embed_model: SentenceTransformer,
        index: faiss.IndexFlatIP, chunks: list[dict],
        llm_model: str = MODEL) -> dict:
    """Run the full RAG pipeline: retrieve -> prompt -> generate."""
    retrieved = retrieve(question, embed_model, index, chunks)

    if retrieved:
        scores = ", ".join(f"{r['score']:.2f}" for r in retrieved)
        print(f"\n  [Retrieved {len(retrieved)} chunks (scores: {scores})]")
    else:
        print("\n  [No relevant chunks found]")

    messages = build_rag_prompt(question, retrieved)
    response = completion(model=llm_model, messages=messages)

    message = response.choices[0].message
    usage = response.usage

    try:
        cost = completion_cost(completion_response=response)
    except Exception:
        cost = 0.0

    return {
        "answer": message.content,
        "sources": retrieved,
        "input_tokens": usage.prompt_tokens,
        "output_tokens": usage.completion_tokens,
        "cost": cost,
    }


def print_answer(result: dict) -> None:
    """Display the RAG answer with sources and stats."""
    print(f"\n  {result['answer']}")

    if result["sources"]:
        print("\n  Sources:")
        for i, src in enumerate(result["sources"], 1):
            section = src["metadata"]["section"]
            print(f"    [{i}] {section} (score: {src['score']:.2f})")

    in_tok = result["input_tokens"]
    out_tok = result["output_tokens"]
    cost = result["cost"]
    print(f"\n  Tokens: {in_tok} in + {out_tok} out | Cost: ${cost:.4f}")


# ---------------------------------------------------------------------------
# Step 6: Interactive loop
# ---------------------------------------------------------------------------

def main():
    print("=" * 60)
    print("  RAG Q&A — Documentation Assistant")
    print("=" * 60)
    print(f"  Model: {MODEL}")
    print("  Document: Authentication & Security Guide")

    chunks = chunk_document(DOCUMENT)
    print(f"  Chunks: {len(chunks)} indexed")

    print("\n  Loading embedding model...")
    embed_model = SentenceTransformer("all-MiniLM-L6-v2")
    print("  Embedding and indexing chunks...")
    index, _ = build_rag_index(chunks, embed_model)
    print("  Ready! Type /bye to quit.\n")

    total_questions = 0
    total_in_tokens = 0
    total_out_tokens = 0
    total_cost = 0.0

    while True:
        try:
            question = input("You: ").strip()
        except (EOFError, KeyboardInterrupt):
            break

        if not question:
            continue
        if question.lower() in ("/bye", "quit", "exit"):
            break

        total_questions += 1
        result = ask(question, embed_model, index, chunks)
        print_answer(result)
        print()

        total_in_tokens += result["input_tokens"]
        total_out_tokens += result["output_tokens"]
        total_cost += result["cost"]

    total_tokens = total_in_tokens + total_out_tokens
    print("\n" + "=" * 60)
    print("  Session Summary")
    print("=" * 60)
    print(f"  Questions:     {total_questions}")
    print(f"  Total tokens:  {total_tokens} ({total_in_tokens} in + {total_out_tokens} out)")
    print(f"  Total cost:    ${total_cost:.4f}")
    print("=" * 60)


if __name__ == "__main__":
    main()
